import Alert from "./Alert"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Alert,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6595%3A48211",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      severity: figma.enum("Severity", {
        Error: "error",
        Warning: "warning",
        Info: "info",
        Success: "success",
      }),
      variant: figma.enum("Variant", {
        Standard: "standard",
        Filled: "filled",
        Outlined: "outlined",
      }),
      // No matching props could be found for these Figma properties:
      // "onClose": figma.boolean('On Close?'),
      // "action": figma.boolean('Action?'),
      // "instance": figma.instance('↳Instance'),
      // "description": figma.boolean('Description?'),
      // "title": figma.boolean('Title?'),
      // "title": figma.string('↳ Title'),
      // "description": figma.string('↳ Description')
    },
    example: (props) => (
      <Alert severity={props.severity} variant={props.variant}>
        This is a {props.severity} alert with {props.variant} variant
      </Alert>
    ),
  },
)
