import AppBar from "./AppBar"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  AppBar,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=11545%3A171494",
  {
    props: {
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Default: "default",
        "Inherit White": "inherit-white",
        Transparent: "transparent",
      }),
    },
    example: (props) => (
      <AppBar color={props.color}>
        <div>App Bar Content</div>
      </AppBar>
    ),
  },
)
