
import Autocomplete from "./Autocomplete"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Autocomplete,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6570%3A49856",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      readOnly: figma.boolean("Open"),
      open: figma.boolean("Open"),
      openOnFocus: figma.boolean("Open"),
      // No matching props could be found for these Figma properties:
      // "multipleValue": figma.boolean('Multiple Value')
    },
    example: (props) => (
      <Autocomplete
        options={['Option 1', 'Option 2', 'Option 3']}
        readOnly={props.readOnly}
        open={props.open}
        openOnFocus={props.openOnFocus}
      />
    ),
  },
)
