import React from "react"
import Button from "./Button"
// @ts-ignore - Provided by Figma Code Connect runtime; not needed in app build
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6543%3A36744",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      color: figma.enum("Color", {
        Inherit: "inherit",
        Primary: "primary",
        Secondary: "secondary",
        Success: "success",
        Error: "error",
        Info: "info",
        Warning: "warning",
      }),
      disabled: figma.boolean("State"),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
        Large: "large",
      }),
      variant: figma.enum("Variant", {
        Text: "text",
        Outlined: "outlined",
        Contained: "contained",
      }),
      children: figma.string("Label"),
    },
    example: (props) => (
      <Button
        color={props.color}
        disabled={props.disabled}
        size={props.size}
        variant={props.variant}
      >
        {props.children}
      </Button>
    ),
  },
)
