
import CardHeader from "./CardHeader"
import { Avatar } from "./Chip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardHeader,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6583%3A46537",
  {
    props: {
      subheader: figma.boolean("Subheader?"),
      header: figma.string("Header"),
      value: figma.string("↳ Value"),
      instanceSlot: figma.boolean("Instance Slot?"),
      instance: figma.instance("Instance"),
      avatar: figma.boolean("Avatar"),
    },
    example: (props) => (
      <CardHeader
        title="Card Title"
        subheader="Card Subtitle"
        avatar={props.avatar ? <Avatar>H</Avatar> : undefined}
      />
    ),
  },
)
