
import CardActions from "./CardActions"
import Button from "./Button"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardActions,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6676%3A48056",
  {
    props: {},
    example: () => (
      <CardActions>
        <Button size="small" color="primary">Action 1</Button>
        <Button size="small" color="secondary">Action 2</Button>
      </CardActions>
    ),
  },
)
