
import CardContent from "./CardContent"
import Typography from "./Typography"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  CardContent,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6640%3A52022",
  {
    props: {
      instance1: figma.instance("↳ Instance 1"),
      instance2: figma.instance("↳ Instance 2"),
      instanceSlot1: figma.boolean("⮑ Instance Slot 1"),
      instanceSlot2: figma.boolean("⮑ Instance Slot 2"),
    },
    example: (props) => (
      <CardContent>
        <Typography variant="body2" color="text.secondary">
          {props.instanceSlot1 ? "Slot 1 Content" : "Default Content"}
        </Typography>
        {props.instanceSlot2 && (
          <Typography variant="body2" color="text.secondary">
            Slot 2 Content
          </Typography>
        )}
      </CardContent>
    ),
  },
)
