import Card from "./Card"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Card,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=11479%3A243797",
  {
    props: {
      smallScreen: figma.enum("Small Screen", {
        False: "false",
        True: "true",
      }),
      blank: figma.enum("Blank", {
        False: "false",
        True: "true",
      }),
    },
    example: (props) => (
      <Card smallScreen={props.smallScreen} blank={props.blank}>
        Card Content
      </Card>
    ),
  },
)
