
import Chip from "./Chip"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Chip,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6588%3A47683",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      label: figma.string("Label"),
      variant: figma.enum("Variant", {
        Filled: "filled",
        Outlined: "outlined",
      }),
      color: figma.enum("Color", {
        Default: "default",
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
      deletable: figma.boolean("Delete?"),
      disabled: figma.boolean("State"),
    },
    example: (props) => (
      <Chip
        label={props.label}
        variant={props.variant}
        color={props.color}
        size={props.size}
        deletable={props.deletable}
        disabled={props.disabled}
      />
    ),
  },
)
