
import Container from "./Container"
import Typography from "./Typography"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Container,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=7660%3A81184",
  {
    props: {
      maxWidth: figma.enum("Max Width", {
        "Extra Large": "xl",
        Large: "lg",
        Medium: "md",
        Small: "sm",
        "Extra Small": "xs",
      }),
      disGutters: figma.boolean("Dis. Gutters"),
    },
    example: (props) => (
      <Container maxWidth={props.maxWidth} disableGutters={props.disGutters}>
        <Typography variant="body1">Container content</Typography>
      </Container>
    ),
  },
)
