
import ListItem from "./ListItem"
import { ListItemText } from "./ListItem"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  ListItem,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6591%3A48882",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      button: figma.boolean("Divider"),
      dense: figma.boolean("Dense"),
      disableGutters: figma.boolean("Dis. Gutters"),
      divider: figma.boolean("Divider"),
      selected: figma.enum("State", {
        Selected: true,
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      className: figma.string("Label"),
      // No matching props could be found for these Figma properties:
      // "secondText": figma.boolean('Second. Text'),
      // "divider": figma.boolean('Divider'),
      // "leftSlot": figma.boolean('Left Slot?'),
      // "rightSlot": figma.boolean('Right Slot?'),
      // "leftSlot": figma.instance('Left Slot'),
      // "label": figma.string('Label')
    },
    example: (props) => (
      <ListItem
        button={props.button}
        dense={props.dense}
        disableGutters={props.disableGutters}
        divider={props.divider}
        selected={props.selected}
        disabled={props.disabled}
        className={props.className}
      >
        <ListItemText primary="List Item Content" />
      </ListItem>
    ),
  },
)
