
import Paper from "./Paper"
import Typography from "./Typography"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Paper,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6584%3A46711",
  {
    props: {
      instanceSlot: figma.boolean("Instance Slot?"),
      instance: figma.instance("↳ Instance"),
      variant: figma.enum("Variant", {
        Elevation: "elevation",
        Outlined: "outlined",
      }),
      elevation: figma.enum("Elevation", {
        "0": 0,
        "1": 1,
        "2": 2,
        "3": 3,
        "4": 4,
        "5": 5,
        "6": 6,
        "7": 7,
        "8": 8,
        "9": 9,
        "10": 10,
        "11": 11,
        "12": 12,
        "13": 13,
        "14": 14,
        "15": 15,
        "16": 16,
        "17": 17,
        "18": 18,
        "19": 19,
        "20": 20,
        "21": 21,
        "22": 22,
        "23": 23,
        "24": 24,
      }),
      square: figma.boolean("Square"),
    },
    example: (props) => (
      <Paper elevation={props.elevation} square={props.square}>
        <Typography variant="body1">Paper content</Typography>
      </Paper>
    ),
  },
)
