import Switch from "./Switch"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  Switch,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6564%3A39128",
  {
    props: {
      // These props were automatically mapped based on your linked code:
      checkedIcon: figma.enum("Checked", {
        False: false,
        True: true,
      }),
      color: figma.enum("Color", {
        Primary: "primary",
        Secondary: "secondary",
        Error: "error",
        Info: "info",
        Success: "success",
        Warning: "warning",
        Default: "default",
      }),
      disabled: figma.enum("State", {
        Disabled: true,
      }),
      defaultChecked: figma.boolean("Checked"),
      checked: figma.boolean("Checked"),
      readOnly: figma.enum("State", {
        Disabled: true,
      }),
      size: figma.enum("Size", {
        Small: "small",
        Medium: "medium",
      }),
    },
    example: (props) => (
      <Switch
        checkedIcon={props.checkedIcon}
        color={props.color}
        disabled={props.disabled}
        defaultChecked={props.defaultChecked}
        checked={props.checked}
        readOnly={props.readOnly}
        size={props.size}
      />
    ),
  },
)
