import TextField from "./TextField"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from your code props to Figma properties.
 * You should check this is correct, and update the `example` function
 * to return the code example you'd like to see in Figma
 */

figma.connect(
  TextField,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6570%3A48313",
  {
    props: {
      variant: figma.enum("Variant", {
        Standard: "standard",
        Filled: "filled",
        Outlined: "outlined",
      }),
      size: figma.enum("Size", {
        Medium: "medium",
        Small: "small",
      }),
      state: figma.enum("State", {
        Enabled: "enabled",
        Hovered: "hovered",
        Focused: "focused",
        Disabled: "disabled",
        Error: "error",
      }),
      hasValue: figma.enum("Has Value", {
        True: "true",
        False: "false",
      }),
      label: figma.string("Label"),
    },
    example: (props) => (
      <TextField
        variant={props.variant}
        size={props.size}
        state={props.state}
        hasValue={props.hasValue}
        label={props.label}
      />
    ),
  },
)
