
import Toolbar from "./Toolbar"
import Typography from "./Typography"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Toolbar,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6583%3A46318",
  {
    props: {
      menu: figma.boolean("Menu"),
      variant: figma.enum("Variant", {
        Regular: "regular",
        Dense: "dense",
      }),
      smallScreen: figma.boolean("Small Screen"),
    },
    example: (props) => (
      <Toolbar>
        <Typography variant="h6">
          {props.smallScreen ? "Small Screen Toolbar" : "Toolbar Content"}
        </Typography>
      </Toolbar>
    ),
  },
)
