
import Typography from "./Typography"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Typography,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=11609%3A174872",
  {
    props: {
      content: figma.string("Content"),
      variant: figma.enum("Variant", {
        body1: "body1",
        body2: "body2",
        subtitle1: "subtitle1",
        subtitle2: "subtitle2",
        overline: "overline",
        caption: "caption",
        h6: "h6",
        h5: "h5",
        h4: "h4",
        h3: "h3",
        h2: "h2",
        h1: "h1",

      }),
      gutterBottom: figma.boolean("Gutter Bottom"),
    },
    example: (props) => (
      <Typography variant={props.variant} gutterBottom={props.gutterBottom}>
        {props.content}
      </Typography>
    ),
  },
)
