import React from "react"
import CustomCardNew from "./CustomCardNew"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * Updated to map code props to Figma properties and provide
 * an example that forwards mapped props to the component.
 */

figma.connect(
  CustomCardNew,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=15702%3A108812",
  {
    props: {
      title: figma.string("title"),
      subtitle: figma.string("subtitle"),
      content: figma.string("Content"),
    },
    example: (props) => (
      <CustomCardNew
        title={(props as any).title}
        subtitle={(props as any).subtitle}
        content={(props as any).content}
      />
    ),
  },
)
