import React from "react"
import SidebarNavigation from "./SidebarNavigation"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  SidebarNavigation,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=15702%3A111010",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "state": figma.enum('State', {
      //   "Expand": "expand",
      //   "Collapse": "collapse"
      // })
    },
    example: (props) => (
      <SidebarNavigation isExpanded={/* TODO */} onToggle={/* TODO */} />
    ),
  },
)
