import React from "react"
import StarSharp from "./StarSharp"
import figma from "@figma/code-connect"

/**
 * -- This file was auto-generated by Code Connect --
 * None of your props could be automatically mapped to Figma properties.
 * You should update the `props` object to include a mapping from your
 * code props to Figma properties, and update the `example` function to
 * return the code example you'd like to see in Figma
 */

figma.connect(
  StarSharp,
  "https://www.figma.com/design/KLNk6eJCBd573J4Qi5oHVs/Accelerant-MUI-DS-test?node-id=6562%3A39569",
  {
    props: {
      // No matching props could be found for these Figma properties:
      // "size": figma.enum('Size', {
      //   "Large": "large",
      //   "Medium*": "medium-",
      //   "Small": "small"
      // }),
      // "active": figma.enum('Active', {
      //   "False": "false",
      //   "Half": "half",
      //   "Full": "full"
      // }),
      // "hovered": figma.boolean('Hovered')
    },
    example: (props) => <StarSharp />,
  },
)
